services:
  php-ccha-backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: meu-php
    ports:
      - 8000:80
    volumes:
      - "C:/projects/ccha-backend:/var/www/html"
    links:
      - db

  db: 
    image: mysql:latest
    container_name: mysql.php
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root